In [1]:
import pandas as pd
import mysql.connector

In [28]:
word_if = "/home/ryan/Downloads/Words - Words.csv"
word_of = "words.json"

quote_if = "/home/ryan/Downloads/Words - Quotes.csv"
quote_of = "quote.json"

connection = "mysql://localhost:3009/wurdee"

In [36]:
word_df = pd.read_csv(word_if, names=['word', 'pos', 'definition'])#.dropna()
word_df = word_df[word_df["word"].notna()]
word_df['pos'] = word_df['pos'].replace('n', 'noun')
word_df['pos'] = word_df['pos'].replace('a', 'adjective')
word_df['pos'] = word_df['pos'].replace('v', 'verb')
word_df.to_json(word_of, orient='records')
word_df.head(100)

                word   pos                                         definition
0               astr  noun  the frustration of being stuck in one body, th...
2           lutalica  noun  the part of your identity that doesn't fit int...
4               opia  noun  the ambiguious intensity of looking someone in...
6          liberosis  noun               the desire to care less about things
8              Yugen  noun  a profound awareness of the universe that trig...
..               ...   ...                                                ...
203         Paroxysm  noun                         sudden outburst of emotion
207        Scintilla  noun  a tiny, brilliant flash or spark, a small thin...
209   Eleutheromania  noun     an intense and irresistible desire for freedom
211      Alexithymia  noun  an inability to describe emotions in a verbal ...
213  Pisanthrophobia  noun  fear of trusting people due to past experience...

[100 rows x 3 columns]

In [12]:
quote_df = pd.read_csv(quote_if, names=['source','quote']).dropna()
quote_df.head()

         source                                              quote
0  Isaac Asimov  The saddest aspect of life right now is that s...
1  Albert Camus                        I rebel; therefore I exist.
2   Victor Hugo  You who suffer because you love, love still mo...
3      Voltaire  God is a comedian playing to an audience too a...
4   John Lennon  Everything is going to be okay in the end, and...